name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   phpunit:
    name: PHP-${{ matrix.php_version }}-${{ matrix.perfer }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - 5.6
          - 7.0
          - 7.1
          - 7.2
          - 7.3 
        perfer:
          - stable
          - lowest
    container:
      image: nauxliu/php-ci-image:${{ matrix.php_version }}
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: composer update --prefer-dist --no-interaction --no-suggest --prefer-${{ matrix.perfer }}
    - name: Run Test
      run: composer test
